language: go
services:
- docker
before_install:
- docker build -t jchorl/golang .
script:
- docker run -v ${TRAVIS_BUILD_DIR}:/src:ro -w /src jchorl/golang go test .
- cd ${TRAVIS_BUILD_DIR}/examples
- LANGUAGE=js docker-compose build
- LANGUAGE=js docker-compose run client
- LANGUAGE=python docker-compose build
- LANGUAGE=python docker-compose run client
- LANGUAGE=go docker-compose build
- LANGUAGE=go docker-compose run client
- LANGUAGE=ruby docker-compose build
- LANGUAGE=ruby docker-compose run client
- docker run -e GOOS=js -e GOARCH=wasm -v ${TRAVIS_BUILD_DIR}:/src -w /src jchorl/golang
  go build -o main.wasm
deploy:
  provider: script
  skip_cleanup: true
  script: docker run -e NETLIFY_TOKEN -v ${TRAVIS_BUILD_DIR}:/src:ro -w /src node:13.1 sh -c "npm install -g netlify-cli && netlify deploy --site=6e10df31-caed-4f73-8760-490d9f78db01 --auth=$NETLIFY_TOKEN --dir=. --prod"
